name: otherChoice
favicon: null
layout_spectrum: 0.76721
title: 'Find it, love it, reserve it'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: awareness
    item: null
    url: null
